### ISSUE TITLE
Size of sponsor logos should honour contract

### ISSUE THREAD

**Issue by ignasi35** [scbcn/scbcn.github.io#37]
* Based on the [Collaboration opportunities slides](https://docs.google.com/presentation/d/15dLCtVpJAXMkPEW7EHAaCDc7Cql-HfjtJbyu9ymjv0w/edit#slide=id.g393d986048_1_190) we should have different logo sizes for each sponsor type:
    * Bronze: 1x
    * Silver & Gold: 2x
    * Platinum: 3x
* Respect the same height in all the sponsor [sponsor images](https://github.com/scbcn/scbcn.github.io/tree/master/assets/img/sponsors). Search for images with logo in the left side of the image and the text in the right one instead of square format. Raise your hand in case you don't find them and we'll ask for them to the sponsors.
* Reduce [sponsor images size](https://github.com/scbcn/scbcn.github.io/tree/master/assets/img/sponsors) ([`schibsted.png`](https://raw.githubusercontent.com/scbcn/scbcn.github.io/master/assets/img/sponsors/schibsted.png) for instance is 1440x324px), and [compress them](https://tinypng.com)

**Comment by JavierCane** [comment]
Sorry, the #38 PR only fixes the third point.

I've reopened this issue in order to let anyone contribute with its first 2 points:

* [ ] Based on the [Collaboration opportunities slides](https://docs.google.com/presentation/d/15dLCtVpJAXMkPEW7EHAaCDc7Cql-HfjtJbyu9ymjv0w/edit#slide=id.g393d986048_1_190) we should have different logo sizes for each sponsor type:
    * Bronze: 1x
    * Silver & Gold: 2x
    * Platinum: 3x
* [ ] Respect the same height in all the sponsor [sponsor images](https://github.com/scbcn/scbcn.github.io/tree/master/assets/img/sponsors). Search for images with logo in the left side of the image and the text in the right one instead of square format. Raise your hand in case you don't find them and we'll ask for them to the sponsors.
